{% set name = "pt.darts" %}
{% set version = "0.3" %}

package:
  name: {{ name.replace("pt.", "") }}
  version: {{ version }}

source:
  url: https://github.com/khanrc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  number: 0
  noarch: python
  script:
    - cp -r $SRC_DIR $SP_DIR/{{ name.replace("pt.", "") }}

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - graphviz
    - pytorch >=0.4.1
    - torchvision
    - tensorboard
    - tensorboardx

test:
  imports:
    - darts
about:
  home: https://github.com/khanrc/pt.darts
  summary: Differentiable Architecture Search
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/khanrc/pt.darts

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
